name: better_me_diary
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.2
  auto_route: ^0.6.7
  uuid: ^2.2.2
  get_it: ^4.0.4
  meta: ^1.1.8
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.14.0+2
  injectable: ^1.0.4
  flushbar: ^1.10.4
  json_annotation: ^3.0.1
  styled_widget: ^0.2.1+2
  flutter_hooks: ^0.13.2
  time: ^1.3.0
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.1
  reorderables: ^0.3.2
  provider: ^4.3.2+1
  implicitly_animated_reorderable_list: ^0.2.3
  flutter_slidable: ^0.5.7
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.14
  path: ^1.7.0
  permission_handler: ^5.0.1+1
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  build_runner:
  freezed: ^0.11.6
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true
  
  assets:
    - lang/en.json
    - lang/sk.json
